config/routes.rb
Rails.application.routes.draw do
  
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # THE IDEAS CONTROLLER
  resources :ideas do
    resources :likes, only: [:create, :destroy]
    resources :joins, only: [:create, :destroy]
  end

  # THE JOINS CONTROLLER
  # This is to allow us to have a page showing all the users who have joined
  resources :joins, only: [:index]

  # THE USERS CONTROLLER
  resources :users, only: [:create, :new]

  # THE SESSIONS CONTROLLER
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "ideas#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    can :manage, Idea do |i|
      i.user == user
    end
  end
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  has_many :joins, dependent: :destroy
  has_many :joined_users, through: :joins, source: :user

  validates :title, presence: true, uniqueness: true

  # Uses the full name method defined in the users model.
  def user_full_name
    user.full_name if user
  end

  def like_for(user)
    likes.find_by_user_id(user)
  end

  def join_for(user)
    joins.find_by_user_id(user)
  end
end

app/models/join.rb
class Join < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea

  validates :user_id, :idea_id, presence: true
  validates :user_id, uniqueness: {scope: :idea_id}

  validate :users_cant_join_their_ideas

  private

  def users_cant_join_their_ideas
    return if user.nil? or idea.nil?
    if user_id == idea.user_id
      errors[:base] = "A user can't join their own ideas"
    end
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea

  validates :user_id, :idea_id, presence: true
  validates :user_id, uniqueness: {scope: :idea_id}

  validate :users_cant_like_their_ideas

  private

  def users_cant_like_their_ideas
    return if user.nil? or idea.nil?
    if user_id == idea.user_id
      errors[:base] = "A user can't like their own ideas"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ideas, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_ideas, through: :likes, source: :idea
  
  has_many :joins, dependent: :destroy
  has_many :joined_ideas, through: :joins, source: :idea

  has_secure_password

  validates :password, length: {minimum: 6}, on: :create
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def full_name
    "#{first_name} #{last_name}".titleize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if user_signed_in?
  end
  helper_method :current_user

  # It is not necessary to make it a helper method since the views have no need
  # to access this method
  def sign_in(user)
    session[:user_id] = user.id
  end

  def authenticate_user
    # if session[:user_id] is nil we redirect to the sign in page
    redirect_to new_session_path, notice: "Please Sign in." unless user_signed_in?
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
    @ideas = Idea.all
  end

  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  def edit
  end

  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def find_idea
      @idea = Idea.find(params[:id])
    end

    def idea_params
      params.require(:idea).permit(:title, :body)
    end

    def authorize_user
      unless can? :manage, @idea
      # if @question.user != current_user
        redirect_to root_path, alert: "ACCESS DENIED!"
      end
    end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController

  before_action :authenticate_user

  def index
    # This returns table of ideas the current user has joined
    @join = current_user.joined_ideas
  end

  def create
    idea = Idea.find(params[:idea_id])
    join = Join.new(idea: idea, user: current_user)
    if join.save
      redirect_to idea, notice: "Idea joined!"
    else
      redirect_to idea, alert: "Join failed. Users unable to join own ideas."
    end
  end

  def destroy
    join = current_user.joins.find(params[:id])
    idea = Idea.find(params[:idea_id])
    join.destroy
    redirect_to idea, notice: "Unjoined idea."
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user

  def create
    idea = Idea.find(params[:idea_id])
    like = Like.new(idea: idea, user: current_user)
    if like.save
      IdeasMailer.notify_idea_owner(idea, current_user).deliver_later
      redirect_to idea, notice: "Liked!"
    else
      redirect_to idea, alert: "Like failed. Users unable to like own ideas."
    end
  end

  def destroy
    like = current_user.likes.find(params[:id])
    idea = Idea.find(params[:idea_id])
    like.destroy
    redirect_to idea, notice: "Un-liked"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
      user = User.find_by_email params[:email]
      if user && user.authenticate(params[:password])
        sign_in(user)
        redirect_to root_path, notice: "Signed in!"
      else
        flash[:alert] = "Wrong credentials"
        render :new
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to root_path, notice: "Sign out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email,
                                               :password, :password_confirmation)
    @user = User.new user_params
    if @user.save
      # if the user is logged in then it will return the user id. If they aren't
      # logged in then session[:user_id] will return nil. Then we can use this
      # to prompt you to login.
      sign_in(@user)
      redirect_to root_path, notice: "User Created!"
    else
      render :new
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Creator</th>
      <th>Idea</th>
      <th>Joined Users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.user_full_name %></td>
        <td><%= idea.body %></td>
        <td><%= idea.joins.count %></td>
        <td><%= link_to 'Show', idea %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice || alert %></p>

<!-- <p><%= @idea.errors.full_messages.join(", ") %></p> -->

<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p> <strong>Created by:</strong><%= @idea.user_full_name if @idea.user %></p>

<p>
  <strong>Idea:</strong>
  <br>
  <%= @idea.body %>
</p>

<!-- Adding the Like/Un-like  -->
<hr align="left" width="30%">
  <% like = @idea.like_for(current_user) %>
  Like:
  <% if like %>
    <%= link_to fa_icon("thumbs-up"), idea_like_path(@idea, like), method: :delete, class:"like-fav-icon"  %>
  <% else %>
    <%= link_to fa_icon("thumbs-o-up"), idea_likes_path(@idea), method: :post, class:"like-fav-icon" %>
  <% end %>
  (<%= @idea.likes.count %>) |
<!-- End of Like/Un-like -->

<!-- Adding the option to join -->
<% join = @idea.join_for(current_user) %>
Join Idea:
<% if join %>
  <%= link_to fa_icon("check-square-o"), idea_join_path(@idea, join), method: :delete, class:"like-fav-icon"  %>
<% else %>
  <%= link_to fa_icon("square-o"), idea_joins_path(@idea), method: :post, class:"like-fav-icon" %>
<% end %>
<hr align="left" width="30%">
<!-- End of join -->

<!-- Adding List of joined users -->
<h3>Joined Users:</h3>
<ul>
  <% @idea.joined_users.each do |user| %>
    <li><%=user.full_name%></li>
  <% end %>
</ul>
<!-- End of joined used -->

<br>
<%# If the user has the authorization to edit show edit link %>
<% if can? :edit, @idea %>
  <%= link_to "Edit", edit_idea_path(@idea) %> |
<% end %>

<% if can? :destroy, @idea %>
  <%= link_to "Delete",
             idea_path(@idea),
             method: :delete,
             data: {confirm: "Are you sure you want to delete #{@idea.title}?"} %> |
<% end %>

<%= link_to 'Back', ideas_path %>

app/views/joins/index.html.erb
<h1>All Joined Questions</h1>

<table class="table table-striped">
  <% @join.each do |join| %>
    <tr>
      <td><%= link_to join.title, idea_path(join) %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareIdeas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <style>
    body {
      margin: 75px;
    }

    .dropdown {
      padding: 15px 30px 0px 20px;
      color: rgb(113, 111, 111);
    }
  </style>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <a class="navbar-left" href="#"><%= image_tag "logo.png" %></a>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", ideas_path %></li>
        <li><%= link_to "All Ideas", ideas_path %></li>
        <li><%= link_to "New Idea", new_idea_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "All Joined Ideas", joins_path %></li>
          <li><%= link_to "Log out", sessions_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_session_path%></li>
          <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>

      <!--  <li>
          <div class="dropdown">
          <span class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Posts<span class="caret"></span>
          </span>
            <ul class="dropdown-menu">
              <li>
                <% if user_signed_in? %>
                  <%# link_to "All Favs", favourites_path %>
                  <%# link_to "Log out", sessions_path, method: :delete %>
                <% else %>
                  <%# link_to "Login", new_session_path%>
                  <%# link_to "Sign Up", new_user_path %>
                <% end %>
              </li>
            </ul>
          </div>
        </li>  Dropdown doesn't appear correct if there is time later! -->

      </ul>
    </div>
  </nav>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= @user.errors.full_messages.join(", ") %>
<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
<% end %>